[package]
name = "qdo"
version = "0.2.2"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tera = "1.12.1"
once_cell = "1.8.0" 
structopt = { version = "0.3", default-features = false }
rust-embed="6.2.0"
anyhow = { version = "1.0" }