[package]
name = "qdo"
version = "0.3.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tera = "1.12.1"
once_cell = "1.8.0"
clap = "3.0.0-beta.5"
rust-embed = "6.2.0"
anyhow = { version = "1.0" }
chrono = "0.4.19"
